version: '{build}'
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
nuget:
  disable_publish_on_pr: true
build_script:
- dotnet build nanoid-net.sln -c Release -v q /nologo
- dotnet pack src/Nanoid/Nanoid.csproj -c Release -o .\artifacts --include-symbols --no-build
test_script:
- dotnet test test/Nanoid.Test/Nanoid.Test.csproj --configuration Release  --no-build

artifacts:
- path: .\artifacts\**\*.*nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: 8Op1aVemdwZjJSCL+FHAd0gW8SZiOuh97XuFfWKyBFbM2D0IJVXZwaKo6C0rav8u
  on:
    appveyor_repo_tag: true